baseurl = "https://www.buffalo.edu/"
title = "Doyle Research Lab"
languageCode = "en-us"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[params]
    viewMorePostLink = "/blog/"
    author = "Scott Doyle"
    style = "ub"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "scottdoy@buffalo.edu"

    about_us = "<p>Our lab uses <b>machine learning</b>, <b>3D modeling</b>, and <b>data visualization</b> to study biology and medicine. We develop methods with clinical and basic science applications. If this sounds exciting, please get in touch.</p>"
    copyright = "Copyright (c) 2016, Scott Doyle; all rights reserved. This site is not reviewed, monitored, or endorsed by the University at Buffalo."
    date_format = "2006-01-02"
    logo = "img/logo.png"
    address = """<p><strong>Doyle Laboratory</strong>
        <br>208 Farber Hall
        <br>3435 Main Street
        <br>Buffalo, NY 14214
        <br>USA
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[params.menu]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[params.menu]]
    name = "About"
    url  = "/about/"
    weight = 4

[[params.menu]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

# Top Carousel
#   All carousel items are defined in their own files. You can find example
#   items at 'exampleSite/data/carousel'. For more informtion take a look at the
#   README.
[params.carousel]
    enable = true

# Features of the Lab
#    All features are defined in their own files. You can find example items
#    at 'exampleSite/data/features'.
#    For more informtion take a look at the README.
[params.features]
    enable = true

# Description of active lab projects
# Project images should be put in 'static/img/projects'
# Banner / header images should be 350x350
# Images in the body of the document should be 1000x300
[params.projects]
    enable = true
    title = "Active Research Projects"
    subtitle = "Our research projects cover a wide range of disciplines. Click to learn more."

# Ad for top 4 recent posts
# Blog banner images should be 1000x750 JPG files (or whatever files)
[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "On our blog, we collect news from our lab, developments in the field, and technical information we think might be helpful."

# Team Section (https://github.com/digitalcraftsman/hugo-agency-theme)
#   All team member's pictures are stored under 'static/img/team'. Suggestion:
#   Image size should be at least 360px*360px or the alignment might be
#   affected.
[params.team]
  enable = true
  #center = true
  title = "Doyle Lab Members"
  subtitle = ""# "Meet the team of talented, passionate scientists in our research group."
  description = "We are recruiting! If you are passionate about your work and are interested in our field, please get in touch!"

#[params.testimonials]
#    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
#    title = "Testimonials"
#    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

#[params.see_more]
#    enable = false
#    icon = "fa fa-file-code-o"
#    title = "Do you want to see more?"
#    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
#    link_url = "#"
#    link_text = "Check other homepages"

# Possibly use this for a "Teaching" section
#    All clients are defined in their own files. You can find example items at
#    'exampleSite/data/clients'. For more informtion take a look at the README.
#    Put client logos into 'static/img/clients'
#[params.clients]
#    enable = false
#    title = "Teaching"
#    subtitle = ""
